version: '3.5'
services:
  db:
    image: postgres
    network_mode: host
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
    volumes:
      - ./conf/postgres/:/docker-entrypoint-initdb.d/
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.50'
    #       memory: '1GB'
